USE [DBDBAASSISTS]
GO

/****** 
DATA: 
DESENVOLVEDOR: GABRIEL QUINTELLA
PROJETO: BLOG DBAASSISTS - SÉRIE NÃO MEXA NOS MEUS COMPONENTES
OBJETIVO: SCRIPT USADO PARA CRIAÇÃO DO BANCO DE DADOS [DBDBAASSISTS]  
******/

-- LIMPA TABELA [dbo].[consulta_vagas]
TRUNCATE TABLE [dbo].[consulta_vagas]
GO

-- ALTERA COLUNA QT_VAGAS PARA INT
ALTER TABLE [dbo].[consulta_vagas] ALTER COLUMN [QT_VAGAS] INT
GO