USE [DBDBAASSISTS]
GO

/****** 
DATA: 
DESENVOLVEDOR: GABRIEL QUINTELLA
PROJETO: BLOG DBAASSISTS - SÉRIE NÃO MEXA NOS MEUS COMPONENTES
OBJETIVO: SCRIPT USADO PARA CRIAÇÃO DO BANCO DE DADOS [DBDBAASSISTS]  
******/

-- CREATE TABELA [dbo].[total_cargo]
CREATE TABLE dbo.total_cargo(
CD_CARGO VARCHAR(200)
,DS_CARGO VARCHAR(200)
,QT_VAGAS int
)
GO