USE [DBDBAASSISTS]
GO

/****** Object:  Table [dbo].[tb_vagas_cargo]    Script Date: 06/12/2021 22:02:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tb_vagas_cargo](
	[ID_CARGO] [int] NOT NULL,
	[QT_VAGAS] INT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_CARGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


