

IF EXISTS (SELECT 1 FROM SYS.TABLES T, SYS.SCHEMAS S WHERE T.schema_id = S.schema_id AND T.name = 'VENDAS' AND S.name = 'dbo')
DROP TABLE dbo.VENDAS
GO

CREATE TABLE dbo.VENDAS
(
NOME_LOJA VARCHAR(100)
,MES VARCHAR(100)
,VALOR DECIMAL(23,3)
)
GO