USE [master]
GO

/****** 
DATA: 
DESENVOLVEDOR: GABRIEL QUINTELLA
PROJETO: BLOG DBAASSISTS - SÉRIE NÃO MEXA NOS MEUS COMPONENTES
OBJETIVO: SCRIPT USADO PARA CRIAÇÃO DO BANCO DE DADOS [DBDBAASSISTS]  
******/

-- VERIFICA SE O BANCO DE DADOS EXISTE
IF NOT EXISTS (SELECT 1 FROM SYS.databases WHERE NAME = 'DBDBAASSISTS')

-- SCRIPT DE CRIAÇÃO
CREATE DATABASE [DBDBAASSISTS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBDBAASSISTS', FILENAME = N'D:\SQL2012\DADOS\DBDBAASSISTS.mdf' , SIZE = 16448KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DBDBAASSISTS_log', FILENAME = N'D:\SQL2012\LOG\DBDBAASSISTS_log.ldf' , SIZE = 13888KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
